### PR TITLE
Corrections to Called ID applet, should now be working 

### PR DESCRIPTION
**Pull request by gegere**
The edits in this commit fix and resolve the issues with this applet / plugin.

### CODE REVIEW

**Comment by chiragnirmal** [comment]
Hi Gegere. Thanks for the fix. I am new to Git. Can you please tell me where I can find the latest fixed code? Is it in your fork or in the main line?

**Comment by gegere** [comment]
Hello @chiragnirmal all you should need to do is review my code and merge it into a fork of this repo.

Give a Google, "merge a pull request on GitHub" that should guide you well.

If @kmorrill completes this merge request the new working version will be on the master branch of this repo.

**Comment by kernworks** [comment]
This looks ok to me. if @kmorrill doesnt merge this soon, we should update the plugins wiki to point to the version from @gegere.

**Comment by gegere** [comment]
@kernworks this would be great. Should I reach out to a member of the managing Twilio / OpenVBX team?

**Comment by kmorrill** [comment]
Hey guys, sorry I haven't looked at this repo in ages.  What kind of testing has happened on this PR?

**Comment by gegere** [comment]
Well testing is important but this is isn't too complex. There was an issue with the plugin format and I corrected it. At this point I have been using it for years while continuing to update the version of OpenVBX.

**Pull request merged**
